### ISSUE TITLE
Some WALS fixes

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#75]
- The language [Rushan](http://wals.info/languoid/lect/wals_code_rsh) should be renamed Shughni.
- [Kurdish (Central)](http://wals.info/languoid/lect/wals_code_krd) has the wrong ISO code in WALS. It should be ckb.
- [Khvarshi](http://wals.info/languoid/lect/wals_code_khv) should be spelled Khwarshi.
- [Wu (Changchow)](http://wals.info/languoid/lect/wals_code_wuc) should be renamed as just Wu.
- [Ke'o](http://wals.info/languoid/lect/wals_code_keo) should be renamed Keo.
- [Mugil](http://wals.info/languoid/lect/wals_code_mug) should be renamed Bargam.
- [Kiwai](http://wals.info/languoid/lect/wals_code_kiw) should be renamed Kiwai (Southern) and the corresponding ISO code should be just kjd rather than both kjd and kiw.
- [Yanesha'](http://wals.info/languoid/lect/wals_code_amu) should be renamed Amuesha.
- [Parecis](http://wals.info/languoid/lect/wals_code_prc) should be renamed Paresi. Also, its location should be changed to 57d30W,14dS.

**Comment by xflr6** [comment]
Also link [Kurdish (Central)](http://wals.info/languoid/lect/wals_code_krd) to [cent1972](http://glottolog.org/resource/languoid/id/cent1972) instead of [nort2641](http://glottolog.org/resource/languoid/id/nort2641)?
https://github.com/clld/wals3/blob/76aeee612b0d52636ee0f15dc839b015c39f75f5/migrations/pending/update_biq_mxx_dan_pkm_acr_guq_rsh_krd_khv_wuc_%20keo_mug_kiw_amu_prc_don.py#L48L51

Also link  [Kiwai](http://wals.info/languoid/lect/wals_code_kiw) to [sout2949](http://glottolog.org/resource/languoid/id/sout2949)?
https://github.com/clld/wals3/blob/76aeee612b0d52636ee0f15dc839b015c39f75f5/migrations/pending/update_biq_mxx_dan_pkm_acr_guq_rsh_krd_khv_wuc_%20keo_mug_kiw_amu_prc_don.py#L64-L68
